export const UPDATE_USER_ID = 'UPDATE_USER_ID';
export const UPDATE_USER_NAME = 'UPDATE_USER_NAME';
export const UPDATE_USER_EMAIL = 'UPDATE_USER_EMAIL';
export const UPDATE_USER_PASSWORD = 'UPDATE_USER_PASSWORD';
export const UPDATE_USER_IS_ADMIN = 'UPDATE_USER_IS_ADMIN';
export const UPDATE_USER_LOGGED_IN = 'UPDATE_USER_LOGGED_IN';

export const UPDATE_DATE_FROM = 'UPDATE_DATE_FROM';
export const UPDATE_DATE_TO = 'UPDATE_DATE_TO';
export const UPDATE_ROOM_TYPE = 'UPDATE_ROOM_TYPE';
export const UPDATE_GUESTS = 'UPDATE_GUESTS';
export const UPDATE_ROOMS = 'UPDATE_ROOMS';
export const UPDATE_GUEST_NAME = 'UPDATE_GUEST_NAME';
export const UPDATE_GUEST_NUMBER = 'UPDATE_GUEST_NUMBER';
export const UPDATE_ALL_BOOKINGS = 'UPDATE_ALL_BOOKINGS';